CXX = g++
CPPUTEST_HOME = /Users/vodde/workspace/cpputest
CPPFLAGS += -I$(CPPUTEST_HOME)/include
CXXFLAGS += -include $(CPPUTEST_HOME)/include/CppUTest/MemoryLeakDetectorNewMacros.h
CFLAGS += -include $(CPPUTEST_HOME)/include/CppUTest/MemoryLeakDetectorMallocMacros.h
LD_LIBRARIES = -L$(CPPUTEST_HOME)/lib -lCppUTest -lCppUTestExt
TARGET = TEST
SRCS = main.cpp test.cpp AllTests.cpp
OBJS = main.o test.o AllTests.OBJS

all: $(TARGET)

$(TARGET): $(OBJS)
		echo $(OBJS)
		$(CXX) -o $@ $^ $(CXXFLAGS) $(LD_LIBRARIES)
		
clean:
		rm -rf *.o
